logging.file: logs/application.log
logging:
  level:
      org:
        springframework:
          web: DEBUG
        hibernate: DEBUG
server:
  port: 8080
#  port: 8090
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/prod
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update


