logging.file: logs/application.log
logging:
  level:
      org:
        springframework:
          web: DEBUG
        hibernate: DEBUG
server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-wz9g00250r96flyq8ro.mysql.rds.aliyuncs.com:3306/test
    username: root
    password: Aa12345!@#$%
#    password: oocl
#    password: 123456
  jpa:
    hibernate:
      ddl-auto: update

#jasypt:
#  encryptor:
#    password: G0CvDz7oJn6
