logging.file: logs/application.log
logging:
  level:
      org:
        springframework:
          web: DEBUG
        hibernate: DEBUG
server:
  port: 8090
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Test
    username: root
    password: oocl
  jpa:
    hibernate:
      ddl-auto: update
